#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sat Dec  5 09:03:40 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class NozomiDownloader(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NozomiDownloader.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((900, 600))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.btnYoutube = wx.Button(self.panel_1, wx.ID_ANY, u"유튜브 개발자 라라")
        self.tbConsole = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.HSCROLL | wx.TE_MULTILINE | wx.TE_READONLY)
        self.tbPositiveTags = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tbNegativeTags = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tbDirectoryName = wx.TextCtrl(self.panel_1, wx.ID_ANY, "Downloads")
        self.btnToggleStart = wx.Button(self.panel_1, wx.ID_ANY, "Start Download")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: NozomiDownloader.__set_properties
        self.SetTitle("Nozomi Downloader (By LaLa)")
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NozomiDownloader.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.btnYoutube, 0, wx.EXPAND, 0)
        lbConsole = wx.StaticText(self.panel_1, wx.ID_ANY, "Console")
        sizer_2.Add(lbConsole, 0, wx.TOP, 5)
        sizer_2.Add(self.tbConsole, 1, wx.EXPAND, 0)
        lbPositiveTags = wx.StaticText(self.panel_1, wx.ID_ANY, u"Positive Tags (여러개의 값은 쉼표로 구분)")
        sizer_2.Add(lbPositiveTags, 0, wx.TOP, 5)
        sizer_2.Add(self.tbPositiveTags, 0, wx.EXPAND, 0)
        lbNegativeTags = wx.StaticText(self.panel_1, wx.ID_ANY, u"Negative Tags (여러개의 값은 쉼표로 구분)")
        sizer_2.Add(lbNegativeTags, 0, wx.EXPAND | wx.TOP, 5)
        sizer_2.Add(self.tbNegativeTags, 0, wx.EXPAND, 0)
        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Download Directory Name (다운로드 위치)")
        sizer_2.Add(label_1, 0, wx.TOP, 5)
        sizer_2.Add(self.tbDirectoryName, 0, wx.EXPAND | wx.TOP, 0)
        sizer_2.Add(self.btnToggleStart, 0, wx.EXPAND | wx.TOP, 5)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class NozomiDownloader

class MyApp(wx.App):
    def OnInit(self):
        self.Window = NozomiDownloader(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Window)
        self.Window.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
